# Generated by Django 4.2.1 on 2023-05-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
